spring.datasource.url=jdbc:postgresql://localhost:5432/streetdom?reWriteBatchedInserts=true
spring.datasource.username=postgres
spring.datasource.password=postgres

jwt.secret=jwt.secret=streetdom-test-only-jwt-secret-key-12345678901234567890
jwt.access-expiration=900000
jwt.refresh-expiration=604800000
jwt.session-max-expiration=1814400000

valhalla.url=http://localhost:8002